Repository Deep-Alchemy/HypeMaths, pull requests merged in 2021-03, with the labels that each got.

#8 Add vector division.
  hypemaths/models/vector.py
Labels: Category: enhancement, Extra: instant fix, Type: normal

#9 Added flatten function and changed the __repr__ function.
  hypemaths/models/matrix.py
Labels: Category: enhancement, Extra: help needed, Meta: good first issue, Type: normal

#10 Fixed a bug
  hypemaths/models/matrix.py
Labels: Category: enhancement, Extra: delayed, Type: normal

#12 Cleanup and docs
  .gitignore
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  docs/Makefile
  docs/api.rst
  docs/changelog.md
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  hypemaths/models/matrix.py
Labels: Category: enhancement, Category: feature, Extra: instant fix, Meta: documentation, Type: moderate
